import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ article }) {   
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <h1 className={styles.title}>
            Welcome to <a href='#'>my website</a>!!
          </h1>
        </section>
        <section>
          <article className={styles.article}>
            <p>
              <b>Name: </b>{article.name}
            </p>
            <p>
              <b>Age: </b>{article.age}
            </p>
            <p>
              <b>Sex: </b>{article.sex}
            </p>
          </article>
        </section>
      </main>

      <footer className={styles.footer}>
        Powered by Awesome!
      </footer>
    </div>
  )
}


export async function getServerSideProps() {
  const domain = "https://test-vercel-project-e7cjz3vc1-johnpiapian.vercel.app/";
  const res = await fetch(`${domain}/api/person`);
  let data = await res.json()

  return {
    props: {
      article: data
    }
  }
}