import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <h1 className={styles.title}>
            Welcome to <a href='#'>my website</a>!
          </h1>
        </section>
        <section>
          <article className={styles.article}>
            <p>
              <b>Name:</b> John
            </p>
            <p>
              <b>Age:</b> 23
            </p>
            <p>
              <b>Sex:</b> Male
            </p>
          </article>
        </section>
      </main>

      <footer className={styles.footer}>
        Powered by Awesome!
      </footer>
    </div>
  )
}
