import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home({article}) {   
  
  console.log(article);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <h1 className={styles.title}>
            Welcome to <a href='#'>my website</a>!!
          </h1>
        </section>
        <section>
          <article className={styles.article}>
            <p>
              <b>Name: </b>{article.name}
            </p>
            <p>
              <b>Age: </b>{article.age}
            </p>
            <p>
              <b>Sex: </b>{article.sex}
            </p>
          </article>
        </section>
      </main>

      <footer className={styles.footer}>
        Powered by Awesome!
      </footer>
    </div>
  )
}


export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/person");
  let data = await res.json()

  return {
    props: {
      article: data
    }
  }
}